ALTER TABLE Pizza_Types
ADD PRIMARY KEY (Pizza_Type_ID);

ALTER TABLE Pizzas
ADD PRIMARY KEY (Pizza_ID);

ALTER TABLE Orders
ADD PRIMARY KEY (Order_ID);

ALTER TABLE Order_Details
ADD PRIMARY KEY (Order_Details_ID);